"""
Slide processing service
Handles PowerPoint file extraction, image conversion, and text extraction
"""
from pptx import Presentation
from PIL import Image
import io
import os
import subprocess
import tempfile
from typing import List, Dict
from app.core.config import settings


class SlideProcessor:
    """Process PowerPoint presentations into individual slides"""
    
    def __init__(self):
        self.slides_dir = settings.SLIDES_DIR
        self.thumbnails_dir = settings.THUMBNAILS_DIR
    
    async def process_presentation(self, file_path: str, filename: str) -> List[Dict]:
        """
        Process a PowerPoint presentation
        Returns list of slide data dictionaries
        """
        prs = Presentation(file_path)
        slides_data = []
        
        base_filename = os.path.splitext(filename)[0]
        
        for idx, slide in enumerate(prs.slides, start=1):
            # Extract text content
            text_content = self._extract_text_from_slide(slide)
            title = self._extract_title_from_slide(slide)
            
            # Convert slide to image
            image_filename = f"{base_filename}_slide_{idx}.png"
            thumbnail_filename = f"{base_filename}_slide_{idx}_thumb.png"
            
            image_path = os.path.join(self.slides_dir, image_filename)
            thumbnail_path = os.path.join(self.thumbnails_dir, thumbnail_filename)
            
            # Convert slide to image using LibreOffice
            try:
                self._convert_slide_to_image(file_path, idx, image_path, thumbnail_path)
            except Exception as e:
                print(f"Error converting slide {idx}: {e}")
                # Fallback to placeholder if conversion fails
                self._create_placeholder_image(image_path, (1920, 1080))
                self._create_placeholder_image(thumbnail_path, (320, 240))
            
            slides_data.append({
                "slide_number": idx,
                "image_path": image_path,
                "thumbnail_path": thumbnail_path,
                "text_content": text_content,
                "title": title
            })
        
        return slides_data
    
    def _extract_text_from_slide(self, slide) -> str:
        """Extract all text from a slide"""
        text_runs = []
        for shape in slide.shapes:
            if hasattr(shape, "text"):
                text_runs.append(shape.text)
        return "\n".join(text_runs)
    
    def _extract_title_from_slide(self, slide) -> str:
        """Extract title from slide if it exists"""
        if slide.shapes.title:
            return slide.shapes.title.text
        return ""
    
    def _convert_slide_to_image(self, pptx_path: str, slide_number: int, image_path: str, thumbnail_path: str):
        """
        Convert a specific slide to image using LibreOffice
        """
        # Try multiple LibreOffice paths
        soffice_paths = [
            '/Applications/LibreOffice.app/Contents/MacOS/soffice',
            'soffice',
            '/usr/bin/soffice',
            '/usr/local/bin/soffice'
        ]
        
        soffice_cmd = None
        for path in soffice_paths:
            try:
                result = subprocess.run([path, '--version'], capture_output=True, timeout=5)
                if result.returncode == 0:
                    soffice_cmd = path
                    break
            except (FileNotFoundError, subprocess.TimeoutExpired):
                continue
        
        if not soffice_cmd:
            raise Exception("LibreOffice not found. Please install LibreOffice.")
        
        # Create a temporary directory for LibreOffice output
        with tempfile.TemporaryDirectory() as temp_dir:
            # Convert entire PPTX to PDF using LibreOffice
            try:
                result = subprocess.run([
                    soffice_cmd,
                    '--headless',
                    '--convert-to', 'pdf',
                    '--outdir', temp_dir,
                    pptx_path
                ], check=True, capture_output=True, timeout=60)
                print(f"LibreOffice output: {result.stdout.decode()}")
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
                print(f"LibreOffice error: {e}")
                raise Exception(f"LibreOffice conversion failed: {e}")
            
            # Find the generated PDF
            pdf_files = [f for f in os.listdir(temp_dir) if f.endswith('.pdf')]
            if not pdf_files:
                raise Exception("No PDF generated by LibreOffice")
            
            pdf_path = os.path.join(temp_dir, pdf_files[0])
            
            # Convert PDF page to image using pdf2image
            try:
                from pdf2image import convert_from_path
                # Try with and without poppler_path
                try:
                    images = convert_from_path(pdf_path, dpi=150)
                except Exception as e:
                    # Try with explicit poppler path for macOS
                    poppler_paths = [
                        '/usr/local/bin',
                        '/opt/homebrew/bin',
                        '/usr/bin'
                    ]
                    for poppler_path in poppler_paths:
                        try:
                            images = convert_from_path(pdf_path, dpi=150, poppler_path=poppler_path)
                            break
                        except:
                            continue
                    else:
                        raise Exception(f"pdf2image failed: {e}. Install poppler: brew install poppler")
                
                if slide_number <= len(images):
                    slide_image = images[slide_number - 1]
                    
                    # Save full-size image
                    slide_image.save(image_path, 'PNG')
                    
                    # Create and save thumbnail
                    thumbnail = slide_image.copy()
                    thumbnail.thumbnail((320, 240), Image.Resampling.LANCZOS)
                    thumbnail.save(thumbnail_path, 'PNG')
                else:
                    raise Exception(f"Slide {slide_number} not found in PDF")
            except ImportError:
                raise Exception("pdf2image library not installed. Run: pip install pdf2image")
    
    def _create_placeholder_image(self, path: str, size: tuple):
        """
        Create a placeholder image
        Fallback when slide conversion fails
        """
        img = Image.new('RGB', size, color=(240, 240, 240))
        img.save(path)

# Made with Bob
